import type {
  Vehiculo,
  Conductor,
  Cliente,
  Obra,
  Ruta,
  Peaje,
  Combustible,
  Despacho,
  Viaje,
  Indicador,
  LogEntry,
} from "@/types/etalum";

export const vehiculos: Vehiculo[] = [
  {
    id: "VEH-01",
    placa: "LWY380",
    marca: "Chevrolet",
    modelo: "NHR",
    año: 2022,
    tipoVehiculo: "Camión turbo",
    capacidadCargaKg: 3500,
    ciudadBase: "Bucaramanga",
    estado: "Activo",
    kmActual: 15000,
    rendimientoKmGal: 9,
    soatVencimiento: "2026-09-15",
    tecnomecanicaVencimiento: "2026-10-20",
    proximoMantenimientoKm: 20000,
    observaciones: "Vehículo principal para rutas Bogotá-Barranquilla",
  },
  {
    id: "VEH-02",
    placa: "NXR036",
    marca: "Chevrolet",
    modelo: "NPR",
    año: 2021,
    tipoVehiculo: "Camión turbo",
    capacidadCargaKg: 5000,
    ciudadBase: "Bucaramanga",
    estado: "Activo",
    kmActual: 23000,
    rendimientoKmGal: 8,
    soatVencimiento: "2026-08-20",
    tecnomecanicaVencimiento: "2026-12-01",
    proximoMantenimientoKm: 25000,
    observaciones: "Carga pesada, rutas largas",
  },
  {
    id: "VEH-03",
    placa: "NXR022",
    marca: "Ford",
    modelo: "Cargo",
    año: 2020,
    tipoVehiculo: "Camión turbo",
    capacidadCargaKg: 4500,
    ciudadBase: "Bucaramanga",
    estado: "Activo",
    kmActual: 18000,
    rendimientoKmGal: 7.5,
    soatVencimiento: "2026-07-10",
    tecnomecanicaVencimiento: "2026-11-15",
    proximoMantenimientoKm: 22000,
    observaciones: "Mantenimiento preventivo pendiente",
  },
  {
    id: "VEH-04",
    placa: "NXR029",
    marca: "Chevrolet",
    modelo: "NHR",
    año: 2023,
    tipoVehiculo: "Camión turbo",
    capacidadCargaKg: 3500,
    ciudadBase: "Bucaramanga",
    estado: "En taller",
    kmActual: 45000,
    rendimientoKmGal: 9,
    soatVencimiento: "2026-12-30",
    tecnomecanicaVencimiento: "2027-01-15",
    proximoMantenimientoKm: 50000,
    observaciones: "En taller por reparación de motor",
  },
  {
    id: "VEH-05",
    placa: "LWY387",
    marca: "Ford",
    modelo: "F-350",
    año: 2022,
    tipoVehiculo: "Camioneta",
    capacidadCargaKg: 2000,
    ciudadBase: "Bucaramanga",
    estado: "Activo",
    kmActual: 12000,
    rendimientoKmGal: 10,
    soatVencimiento: "2026-08-05",
    tecnomecanicaVencimiento: "2026-09-10",
    proximoMantenimientoKm: 15000,
    observaciones: "Transporte de personal y materiales ligeros",
  },
];

export const conductores: Conductor[] = [
  {
    id: "CON-01",
    nombreCompleto: "Cristian Ortiz",
    cedula: "1.234.567",
    categoriaLicencia: "B3",
    licenciaVencimiento: "2026-09-01",
    telefono: "3001234567",
    ciudadBase: "Bucaramanga",
    estado: "Activo",
    vehiculoAsignadoId: "VEH-01",
    placaAsignada: "LWY380",
    fechaIngreso: "2020-01-15",
    observaciones: "Conductor experimentado en rutas largas",
  },
  {
    id: "CON-02",
    nombreCompleto: "Didier Medina",
    cedula: "2.345.678",
    categoriaLicencia: "C2",
    licenciaVencimiento: "2026-12-15",
    telefono: "3009876543",
    ciudadBase: "Bucaramanga",
    estado: "Activo",
    vehiculoAsignadoId: "VEH-02",
    placaAsignada: "NXR036",
    fechaIngreso: "2021-03-10",
    observaciones: "Especialista en carga pesada",
  },
  {
    id: "CON-03",
    nombreCompleto: "William Rueda",
    cedula: "3.456.789",
    categoriaLicencia: "B2",
    licenciaVencimiento: "2026-08-10",
    telefono: "3005554444",
    ciudadBase: "Bucaramanga",
    estado: "Activo",
    vehiculoAsignadoId: null,
    placaAsignada: null,
    fechaIngreso: "2019-06-20",
    observaciones: "Disponible para asignación",
  },
  {
    id: "CON-04",
    nombreCompleto: "Cesar Rangel",
    cedula: "4.567.890",
    categoriaLicencia: "C3",
    licenciaVencimiento: "2027-03-20",
    telefono: "3007778888",
    ciudadBase: "Bucaramanga",
    estado: "Vacaciones",
    vehiculoAsignadoId: "VEH-05",
    placaAsignada: "LWY387",
    fechaIngreso: "2022-01-10",
    observaciones: "En vacaciones hasta el 15 de agosto",
  },
];

export const clientes: Cliente[] = [
  {
    id: "CLI-001",
    nombre: "Constructora del Norte S.A.S.",
    nit: "900.123.456-7",
    contacto: "Juan Pérez",
    telefono: "3001112222",
    email: "juan@cdnorte.com",
    ciudad: "Barranquilla",
    obrasActivas: 8,
    estado: "Activa",
    observaciones: "Principal cliente en Barranquilla",
  },
  {
    id: "CLI-002",
    nombre: "Inmobiliaria Caribe Ltda.",
    nit: "900.987.654-3",
    contacto: "María Gómez",
    telefono: "3003334444",
    email: "maria@caribe.com",
    ciudad: "Cartagena",
    obrasActivas: 5,
    estado: "Activa",
    observaciones: "Obras en Cartagena y Santa Marta",
  },
  {
    id: "CLI-003",
    nombre: "Desarrollos Bogotá S.A.",
    nit: "900.555.777-1",
    contacto: "Carlos Ruiz",
    telefono: "3005556666",
    email: "carlos@desbog.com",
    ciudad: "Bogotá",
    obrasActivas: 12,
    estado: "Activa",
    observaciones: "Mayor volumen de despachos",
  },
];

export const obras: Obra[] = [
  { id: "OB-001", nombre: "Palmanova", torre: "Torre 1", clienteId: "CLI-001", ciudad: "Barranquilla", direccion: "Calle 123 #45-67", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Constructora del Norte", alias: "PN1", observaciones: "" },
  { id: "OB-002", nombre: "Palmanova", torre: "Torre 2", clienteId: "CLI-001", ciudad: "Barranquilla", direccion: "Calle 123 #45-68", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Constructora del Norte", alias: "PN2", observaciones: "" },
  { id: "OB-003", nombre: "Palmanova", torre: "Torre 3", clienteId: "CLI-001", ciudad: "Barranquilla", direccion: "Calle 123 #45-69", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Constructora del Norte", alias: "PN3", observaciones: "" },
  { id: "OB-004", nombre: "Dimaro", torre: "Torre A", clienteId: "CLI-001", ciudad: "Barranquilla", direccion: "Av. Circunvalar 10", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Constructora del Norte", alias: "DMA", observaciones: "" },
  { id: "OB-005", nombre: "Dimaro", torre: "Torre B", clienteId: "CLI-001", ciudad: "Barranquilla", direccion: "Av. Circunvalar 11", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Constructora del Norte", alias: "DMB", observaciones: "" },
  { id: "OB-006", nombre: "Riverbay", torre: "Edif. 1", clienteId: "CLI-002", ciudad: "Cartagena", direccion: "Bocagrande 101", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Inmobiliaria Caribe", alias: "RB1", observaciones: "" },
  { id: "OB-007", nombre: "Riverbay", torre: "Edif. 2", clienteId: "CLI-002", ciudad: "Cartagena", direccion: "Bocagrande 102", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Inmobiliaria Caribe", alias: "RB2", observaciones: "" },
  { id: "OB-008", nombre: "Riverbay", torre: "Edif. 3", clienteId: "CLI-002", ciudad: "Cartagena", direccion: "Bocagrande 103", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Inmobiliaria Caribe", alias: "RB3", observaciones: "" },
  { id: "OB-009", nombre: "Altamar", torre: "Torre 1", clienteId: "CLI-002", ciudad: "Santa Marta", direccion: "Rodadero Norte 55", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Inmobiliaria Caribe", alias: "AT1", observaciones: "" },
  { id: "OB-010", nombre: "Altamar", torre: "Torre 2", clienteId: "CLI-002", ciudad: "Santa Marta", direccion: "Rodadero Norte 56", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Inmobiliaria Caribe", alias: "AT2", observaciones: "" },
  { id: "OB-011", nombre: "Bosque Real", torre: "Casa 1", clienteId: "CLI-003", ciudad: "Bogotá", direccion: "Suba Alta 201", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "BR1", observaciones: "" },
  { id: "OB-012", nombre: "Bosque Real", torre: "Casa 2", clienteId: "CLI-003", ciudad: "Bogotá", direccion: "Suba Alta 202", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "BR2", observaciones: "" },
  { id: "OB-013", nombre: "Bosque Real", torre: "Casa 3", clienteId: "CLI-003", ciudad: "Bogotá", direccion: "Suba Alta 203", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "BR3", observaciones: "" },
  { id: "OB-014", nombre: "Bosque Real", torre: "Casa 4", clienteId: "CLI-003", ciudad: "Bogotá", direccion: "Suba Alta 204", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "BR4", observaciones: "" },
  { id: "OB-015", nombre: "Prado Norte", torre: "Apto 101", clienteId: "CLI-003", ciudad: "Bogotá", direccion: "Prado Veraniego 10", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "PN101", observaciones: "" },
  { id: "OB-016", nombre: "Prado Norte", torre: "Apto 102", clienteId: "CLI-003", ciudad: "Bogotá", direccion: "Prado Veraniego 11", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "PN102", observaciones: "" },
  { id: "OB-017", nombre: "Prado Norte", torre: "Apto 103", clienteId: "CLI-003", ciudad: "Bogotá", direccion: "Prado Veraniego 12", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "PN103", observaciones: "" },
  { id: "OB-018", nombre: "Villa Campestre", torre: "Lote 1", clienteId: "CLI-003", ciudad: "Bucaramanga", direccion: "Floridablanca Km 5", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "VC1", observaciones: "" },
  { id: "OB-019", nombre: "Villa Campestre", torre: "Lote 2", clienteId: "CLI-003", ciudad: "Bucaramanga", direccion: "Floridablanca Km 6", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "VC2", observaciones: "" },
  { id: "OB-020", nombre: "Villa Campestre", torre: "Lote 3", clienteId: "CLI-003", ciudad: "Bucaramanga", direccion: "Floridablanca Km 7", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "VC3", observaciones: "" },
  { id: "OB-021", nombre: "San Francisco", torre: "Bloque 1", clienteId: "CLI-001", ciudad: "Barranquilla", direccion: "Calle 80 #10-20", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Constructora del Norte", alias: "SF1", observaciones: "" },
  { id: "OB-022", nombre: "San Francisco", torre: "Bloque 2", clienteId: "CLI-001", ciudad: "Barranquilla", direccion: "Calle 80 #10-21", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Constructora del Norte", alias: "SF2", observaciones: "" },
  { id: "OB-023", nombre: "Marina del Rey", torre: "Torre 1", clienteId: "CLI-002", ciudad: "Cartagena", direccion: "Manga 301", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Inmobiliaria Caribe", alias: "MR1", observaciones: "" },
  { id: "OB-024", nombre: "Marina del Rey", torre: "Torre 2", clienteId: "CLI-002", ciudad: "Cartagena", direccion: "Manga 302", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Inmobiliaria Caribe", alias: "MR2", observaciones: "" },
  { id: "OB-025", nombre: "Costa Brava", torre: "Villa 1", clienteId: "CLI-002", ciudad: "Santa Marta", direccion: "Bello Horizonte 10", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Inmobiliaria Caribe", alias: "CB1", observaciones: "" },
  { id: "OB-026", nombre: "Costa Brava", torre: "Villa 2", clienteId: "CLI-002", ciudad: "Santa Marta", direccion: "Bello Horizonte 11", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Inmobiliaria Caribe", alias: "CB2", observaciones: "" },
  { id: "OB-027", nombre: "Costa Brava", torre: "Villa 3", clienteId: "CLI-002", ciudad: "Santa Marta", direccion: "Bello Horizonte 12", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Inmobiliaria Caribe", alias: "CB3", observaciones: "" },
  { id: "OB-028", nombre: "El Refugio", torre: "Casa 1", clienteId: "CLI-003", ciudad: "Bogotá", direccion: "Usaquén 501", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "ER1", observaciones: "" },
  { id: "OB-029", nombre: "El Refugio", torre: "Casa 2", clienteId: "CLI-003", ciudad: "Bogotá", direccion: "Usaquén 502", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "ER2", observaciones: "" },
  { id: "OB-030", nombre: "El Refugio", torre: "Casa 3", clienteId: "CLI-003", ciudad: "Bogotá", direccion: "Usaquén 503", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "ER3", observaciones: "" },
  { id: "OB-031", nombre: "La Floresta", torre: "Apto 201", clienteId: "CLI-003", ciudad: "Bucaramanga", direccion: "Cabecera 101", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "LF201", observaciones: "" },
  { id: "OB-032", nombre: "La Floresta", torre: "Apto 202", clienteId: "CLI-003", ciudad: "Bucaramanga", direccion: "Cabecera 102", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "LF202", observaciones: "" },
  { id: "OB-033", nombre: "La Floresta", torre: "Apto 203", clienteId: "CLI-003", ciudad: "Bucaramanga", direccion: "Cabecera 103", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Desarrollos Bogotá", alias: "LF203", observaciones: "" },
  { id: "OB-034", nombre: "Portal del Norte", torre: "Torre A", clienteId: "CLI-001", ciudad: "Barranquilla", direccion: "Murillo 1001", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Constructora del Norte", alias: "PN_A", observaciones: "" },
  { id: "OB-035", nombre: "Portal del Norte", torre: "Torre B", clienteId: "CLI-001", ciudad: "Barranquilla", direccion: "Murillo 1002", estadoDireccion: "Completo", estadoObra: "Activa", fuente: "Constructora del Norte", alias: "PN_B", observaciones: "" },
  { id: "OB-036", nombre: "Portal del Norte", torre: "Torre C", clienteId: "CLI-001", ciudad: "Barranquilla", direccion: "", estadoDireccion: "Falta dirección", estadoObra: "Activa", fuente: "Constructora del Norte", alias: "PN_C", observaciones: "Dirección pendiente de confirmar" },
];

export const rutas: Ruta[] = [
  {
    id: "RT-01",
    origen: "Zona franca Santander, Floridablanca",
    destino: "Cartagena",
    via: "Vía Rionegro",
    distanciaKm: 680,
    tiempoMin: 720,
    peajeReferencia: 45000,
    linkGoogleMaps: "https://maps.google.com/?q=Floridablanca+to+Cartagena",
    ultimaActualizacion: "2026-07-31",
    observaciones: "Ruta principal para obras de Cartagena",
  },
  {
    id: "RT-02",
    origen: "Bucaramanga",
    destino: "Bogotá",
    via: "Vía Piedecuesta",
    distanciaKm: 420,
    tiempoMin: 480,
    peajeReferencia: 32000,
    linkGoogleMaps: "https://maps.google.com/?q=Bucaramanga+to+Bogota",
    ultimaActualizacion: "2026-07-31",
    observaciones: "Acceso a obras de Bogotá",
  },
  {
    id: "RT-03",
    origen: "Barranquilla",
    destino: "Cartagena",
    via: "Vía alterna",
    distanciaKm: 120,
    tiempoMin: 150,
    peajeReferencia: 15000,
    linkGoogleMaps: "https://maps.google.com/?q=Barranquilla+to+Cartagena",
    ultimaActualizacion: "2026-07-31",
    observaciones: "Trayecto corto entre ciudades hermanas",
  },
  {
    id: "RT-04",
    origen: "Bogotá",
    destino: "Barranquilla",
    via: "Vía principal",
    distanciaKm: 950,
    tiempoMin: 1080,
    peajeReferencia: 65000,
    linkGoogleMaps: "https://maps.google.com/?q=Bogota+to+Barranquilla",
    ultimaActualizacion: "2026-07-31",
    observaciones: "Ruta más larga del sistema",
  },
];

export const peajes: Peaje[] = [
  {
    id: "PJ-001",
    nombre: "Peaje Piedecuestas",
    via: "Vía Bucaramanga-Piedecuesta",
    departamento: "Santander",
    categoriaVehiculo: "Categoría II",
    tarifa: 15000,
    fechaActualizacion: "2026-01-15",
    fuente: "ANI",
    observaciones: "",
  },
  {
    id: "PJ-002",
    nombre: "Peaje Variante",
    via: "Vía Bogotá-Girardot",
    departamento: "Cundinamarca",
    categoriaVehiculo: "Categoría III",
    tarifa: 22000,
    fechaActualizacion: "2026-01-15",
    fuente: "ANI",
    observaciones: "",
  },
  {
    id: "PJ-003",
    nombre: "Peaje Cartagena",
    via: "Vía Barranquilla-Cartagena",
    departamento: "Atlántico",
    categoriaVehiculo: "Categoría II",
    tarifa: 18500,
    fechaActualizacion: "2026-01-15",
    fuente: "ANI",
    observaciones: "",
  },
];

export const combustibles: Combustible[] = [
  { id: "COM-0001", fecha: "2026-08-03", ciudad: "Bucaramanga", tipo: "Diésel", precioGalon: 14250, fuente: "Ministerio de Minas", observaciones: "" },
  { id: "COM-0002", fecha: "2026-08-03", ciudad: "Bogotá", tipo: "Diésel", precioGalon: 14800, fuente: "Ministerio de Minas", observaciones: "" },
  { id: "COM-0003", fecha: "2026-08-03", ciudad: "Barranquilla", tipo: "Diésel", precioGalon: 13900, fuente: "Ministerio de Minas", observaciones: "" },
  { id: "COM-0004", fecha: "2026-08-01", ciudad: "Cartagena", tipo: "Diésel", precioGalon: 14100, fuente: "Ministerio de Minas", observaciones: "" },
  { id: "COM-0005", fecha: "2026-07-28", ciudad: "Bucaramanga", tipo: "Diésel", precioGalon: 14000, fuente: "Ministerio de Minas", observaciones: "" },
];

export const despachos: Despacho[] = [
  { id: "DES-0001", fecha: "2026-08-04", dia: "Lunes", obraId: "OB-001", nombreObra: "Palmanova Torre 1", ciudad: "Barranquilla", clienteId: "CLI-001", descripcionCarga: "Vidrio templado 5mm", areaResponsable: "Vidrio", memo: "MEM-001", cot: "COT-1001", responsableAutoriza: "Juan Pérez", estado: "Programado", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-01T08:00:00Z" },
  { id: "DES-0002", fecha: "2026-08-04", dia: "Lunes", obraId: "OB-006", nombreObra: "Riverbay Edif. 1", ciudad: "Cartagena", clienteId: "CLI-002", descripcionCarga: "Perfiles de aluminio", areaResponsable: "Aluminio", memo: "MEM-002", cot: "COT-1002", responsableAutoriza: "María Gómez", estado: "En preparación", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-01T08:15:00Z" },
  { id: "DES-0003", fecha: "2026-08-04", dia: "Lunes", obraId: "OB-011", nombreObra: "Bosque Real Casa 1", ciudad: "Bogotá", clienteId: "CLI-003", descripcionCarga: "Marcos de puertas", areaResponsable: "Ensamble", memo: "MEM-003", cot: "COT-1003", responsableAutoriza: "Carlos Ruiz", estado: "Programado", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-01T08:30:00Z" },
  { id: "DES-0004", fecha: "2026-08-05", dia: "Martes", obraId: "OB-009", nombreObra: "Altamar Torre 1", ciudad: "Santa Marta", clienteId: "CLI-002", descripcionCarga: "Vidrio laminado 8mm", areaResponsable: "Vidrio", memo: "MEM-004", cot: "COT-1004", responsableAutoriza: "María Gómez", estado: "Programado", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-01T09:00:00Z" },
  { id: "DES-0005", fecha: "2026-08-05", dia: "Martes", obraId: "OB-002", nombreObra: "Palmanova Torre 2", ciudad: "Barranquilla", clienteId: "CLI-001", descripcionCarga: "Herramientas de acero", areaResponsable: "Acero", memo: "MEM-005", cot: "COT-1005", responsableAutoriza: "Juan Pérez", estado: "Despachado", viajeAsignadoId: "VIA-0001", observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-01T09:15:00Z" },
  { id: "DES-0006", fecha: "2026-08-05", dia: "Martes", obraId: "OB-015", nombreObra: "Prado Norte Apto 101", ciudad: "Bogotá", clienteId: "CLI-003", descripcionCarga: "Ventanas de aluminio", areaResponsable: "Aluminio", memo: "MEM-006", cot: "COT-1006", responsableAutoriza: "Carlos Ruiz", estado: "Entregado", viajeAsignadoId: "VIA-0002", observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-01T09:30:00Z" },
  { id: "DES-0007", fecha: "2026-08-06", dia: "Miércoles", obraId: "OB-021", nombreObra: "San Francisco Bloque 1", ciudad: "Barranquilla", clienteId: "CLI-001", descripcionCarga: "Paneles de vidrio", areaResponsable: "Vidrio", memo: "MEM-007", cot: "COT-1007", responsableAutoriza: "Juan Pérez", estado: "Programado", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-02T08:00:00Z" },
  { id: "DES-0008", fecha: "2026-08-06", dia: "Miércoles", obraId: "OB-023", nombreObra: "Marina del Rey Torre 1", ciudad: "Cartagena", clienteId: "CLI-002", descripcionCarga: "Estructuras metálicas", areaResponsable: "Acero", memo: "MEM-008", cot: "COT-1008", responsableAutoriza: "María Gómez", estado: "En preparación", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-02T08:15:00Z" },
  { id: "DES-0009", fecha: "2026-08-06", dia: "Miércoles", obraId: "OB-018", nombreObra: "Villa Campestre Lote 1", ciudad: "Bucaramanga", clienteId: "CLI-003", descripcionCarga: "Materiales de ensamble", areaResponsable: "Ensamble", memo: "MEM-009", cot: "COT-1009", responsableAutoriza: "Carlos Ruiz", estado: "Programado", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-02T08:30:00Z" },
  { id: "DES-0010", fecha: "2026-08-07", dia: "Jueves", obraId: "OB-003", nombreObra: "Palmanova Torre 3", ciudad: "Barranquilla", clienteId: "CLI-001", descripcionCarga: "Vidrio esmerilado", areaResponsable: "Vidrio", memo: "MEM-010", cot: "COT-1010", responsableAutoriza: "Juan Pérez", estado: "Despachado", viajeAsignadoId: "VIA-0003", observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-02T09:00:00Z" },
  { id: "DES-0011", fecha: "2026-08-07", dia: "Jueves", obraId: "OB-025", nombreObra: "Costa Brava Villa 1", ciudad: "Santa Marta", clienteId: "CLI-002", descripcionCarga: "Puertas de vidrio", areaResponsable: "Vidrio", memo: "MEM-011", cot: "COT-1011", responsableAutoriza: "María Gómez", estado: "Programado", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-02T09:15:00Z" },
  { id: "DES-0012", fecha: "2026-08-07", dia: "Jueves", obraId: "OB-012", nombreObra: "Bosque Real Casa 2", ciudad: "Bogotá", clienteId: "CLI-003", descripcionCarga: "Barandillas de acero", areaResponsable: "Acero", memo: "MEM-012", cot: "COT-1012", responsableAutoriza: "Carlos Ruiz", estado: "Entregado", viajeAsignadoId: "VIA-0004", observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-02T09:30:00Z" },
  { id: "DES-0013", fecha: "2026-08-08", dia: "Viernes", obraId: "OB-004", nombreObra: "Dimaro Torre A", ciudad: "Barranquilla", clienteId: "CLI-001", descripcionCarga: "Componentes de aluminio", areaResponsable: "Aluminio", memo: "MEM-013", cot: "COT-1013", responsableAutoriza: "Juan Pérez", estado: "Programado", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-03T08:00:00Z" },
  { id: "DES-0014", fecha: "2026-08-08", dia: "Viernes", obraId: "OB-007", nombreObra: "Riverbay Edif. 2", ciudad: "Cartagena", clienteId: "CLI-002", descripcionCarga: "Mamparas de vidrio", areaResponsable: "Vidrio", memo: "MEM-014", cot: "COT-1014", responsableAutoriza: "María Gómez", estado: "Programado", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-03T08:15:00Z" },
  { id: "DES-0015", fecha: "2026-08-08", dia: "Viernes", obraId: "OB-028", nombreObra: "El Refugio Casa 1", ciudad: "Bogotá", clienteId: "CLI-003", descripcionCarga: "Sistemas de ensamble", areaResponsable: "Ensamble", memo: "MEM-015", cot: "COT-1015", responsableAutoriza: "Carlos Ruiz", estado: "En preparación", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-03T08:30:00Z" },
  { id: "DES-0016", fecha: "2026-08-11", dia: "Lunes", obraId: "OB-010", nombreObra: "Altamar Torre 2", ciudad: "Santa Marta", clienteId: "CLI-002", descripcionCarga: "Vidrio de seguridad", areaResponsable: "Vidrio", memo: "MEM-016", cot: "COT-1016", responsableAutoriza: "María Gómez", estado: "Programado", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-04T08:00:00Z" },
  { id: "DES-0017", fecha: "2026-08-11", dia: "Lunes", obraId: "OB-034", nombreObra: "Portal del Norte Torre A", ciudad: "Barranquilla", clienteId: "CLI-001", descripcionCarga: "Perfiles estructurales", areaResponsable: "Acero", memo: "MEM-017", cot: "COT-1017", responsableAutoriza: "Juan Pérez", estado: "Cancelado", viajeAsignadoId: null, observaciones: "Obra suspendida temporalmente", registradoPor: "admin", fechaRegistro: "2026-08-04T08:15:00Z" },
  { id: "DES-0018", fecha: "2026-08-11", dia: "Lunes", obraId: "OB-019", nombreObra: "Villa Campestre Lote 2", ciudad: "Bucaramanga", clienteId: "CLI-003", descripcionCarga: "Accesorios de aluminio", areaResponsable: "Aluminio", memo: "MEM-018", cot: "COT-1018", responsableAutoriza: "Carlos Ruiz", estado: "Programado", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-04T08:30:00Z" },
  { id: "DES-0019", fecha: "2026-08-12", dia: "Martes", obraId: "OB-005", nombreObra: "Dimaro Torre B", ciudad: "Barranquilla", clienteId: "CLI-001", descripcionCarga: "Vidrio temperado", areaResponsable: "Vidrio", memo: "MEM-019", cot: "COT-1019", responsableAutoriza: "Juan Pérez", estado: "Programado", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-04T09:00:00Z" },
  { id: "DES-0020", fecha: "2026-08-12", dia: "Martes", obraId: "OB-029", nombreObra: "El Refugio Casa 2", ciudad: "Bogotá", clienteId: "CLI-003", descripcionCarga: "Insumos varios", areaResponsable: "Almacén", memo: "MEM-020", cot: "COT-1020", responsableAutoriza: "Carlos Ruiz", estado: "Programado", viajeAsignadoId: null, observaciones: "", registradoPor: "admin", fechaRegistro: "2026-08-04T09:15:00Z" },
];

export const viajes: Viaje[] = [
  {
    id: "VIA-0001",
    fecha: "2026-08-04",
    rutaId: "RT-01",
    ciudadDestino: "Cartagena",
    vehiculoId: "VEH-01",
    placa: "LWY380",
    conductorId: "CON-01",
    conductorNombre: "Cristian Ortiz",
    despachosIncluidos: "DES-0002, DES-0008",
    numeroObrasIncluidas: 2,
    horaSalida: "06:00",
    kmInicial: 15000,
    kmFinal: 15680,
    kmRecorridos: 680,
    costoPeajes: 45000,
    consumoGalones: 85,
    costoCombustible: 1198500,
    costoTotal: 1243500,
    estado: "Completado",
    observaciones: "Viaje sin novedad",
    cliente: "Inmobiliaria Caribe Ltda.",
    direccionOrigen: "Zona franca Santander, Floridablanca",
    direccionDestino: "Bocagrande, Cartagena",
    horaLlegada: "18:00",
    cantidadPeajes: 3,
    tiempoRecorridoMin: 720,
  },
  {
    id: "VIA-0002",
    fecha: "2026-08-05",
    rutaId: "RT-02",
    ciudadDestino: "Bogotá",
    vehiculoId: "VEH-02",
    placa: "NXR036",
    conductorId: "CON-02",
    conductorNombre: "Didier Medina",
    despachosIncluidos: "DES-0003, DES-0006",
    numeroObrasIncluidas: 2,
    horaSalida: "05:30",
    kmInicial: 23000,
    kmFinal: 23420,
    kmRecorridos: 420,
    costoPeajes: 32000,
    consumoGalones: 52.5,
    costoCombustible: 777000,
    costoTotal: 809000,
    estado: "Completado",
    observaciones: "Llegada a tiempo",
    cliente: "Desarrollos Bogotá S.A.",
    direccionOrigen: "Bucaramanga",
    direccionDestino: "Suba Alta, Bogotá",
    horaLlegada: "13:30",
    cantidadPeajes: 2,
    tiempoRecorridoMin: 480,
  },
  {
    id: "VIA-0003",
    fecha: "2026-08-07",
    rutaId: "RT-03",
    ciudadDestino: "Barranquilla",
    vehiculoId: "VEH-03",
    placa: "NXR022",
    conductorId: "CON-01",
    conductorNombre: "Cristian Ortiz",
    despachosIncluidos: "DES-0005, DES-0010",
    numeroObrasIncluidas: 2,
    horaSalida: "07:00",
    kmInicial: 18000,
    kmFinal: 18120,
    kmRecorridos: 120,
    costoPeajes: 15000,
    consumoGalones: 16,
    costoCombustible: 222400,
    costoTotal: 237400,
    estado: "Completado",
    observaciones: "Entrega completada",
    cliente: "Constructora del Norte S.A.S.",
    direccionOrigen: "Cartagena",
    direccionDestino: "Calle 123, Barranquilla",
    horaLlegada: "09:30",
    cantidadPeajes: 1,
    tiempoRecorridoMin: 150,
  },
  {
    id: "VIA-0004",
    fecha: "2026-08-07",
    rutaId: "RT-02",
    ciudadDestino: "Bogotá",
    vehiculoId: "VEH-05",
    placa: "LWY387",
    conductorId: "CON-03",
    conductorNombre: "William Rueda",
    despachosIncluidos: "DES-0012",
    numeroObrasIncluidas: 1,
    horaSalida: "06:00",
    kmInicial: 12000,
    kmFinal: 12420,
    kmRecorridos: 420,
    costoPeajes: 32000,
    consumoGalones: 42,
    costoCombustible: 621600,
    costoTotal: 653600,
    estado: "Completado",
    observaciones: "Camioneta para carga ligera",
    cliente: "Desarrollos Bogotá S.A.",
    direccionOrigen: "Bucaramanga",
    direccionDestino: "Suba Alta, Bogotá",
    horaLlegada: "13:00",
    cantidadPeajes: 2,
    tiempoRecorridoMin: 420,
  },
  {
    id: "VIA-0005",
    fecha: "2026-08-08",
    rutaId: "RT-04",
    ciudadDestino: "Barranquilla",
    vehiculoId: "VEH-01",
    placa: "LWY380",
    conductorId: "CON-01",
    conductorNombre: "Cristian Ortiz",
    despachosIncluidos: "DES-0013",
    numeroObrasIncluidas: 1,
    horaSalida: "04:00",
    kmInicial: 15680,
    kmFinal: 16630,
    kmRecorridos: 950,
    costoPeajes: 65000,
    consumoGalones: 105.6,
    costoCombustible: 1468296,
    costoTotal: 1533296,
    estado: "En ruta",
    observaciones: "En curso hacia Barranquilla",
    cliente: "Constructora del Norte S.A.S.",
    direccionOrigen: "Bogotá",
    direccionDestino: "Av. Circunvalar, Barranquilla",
    horaLlegada: "",
    cantidadPeajes: 4,
    tiempoRecorridoMin: 0,
  },
  {
    id: "VIA-0006",
    fecha: "2026-08-11",
    rutaId: "RT-01",
    ciudadDestino: "Cartagena",
    vehiculoId: "VEH-02",
    placa: "NXR036",
    conductorId: "CON-02",
    conductorNombre: "Didier Medina",
    despachosIncluidos: "DES-0014",
    numeroObrasIncluidas: 1,
    horaSalida: "06:00",
    kmInicial: 0,
    kmFinal: 0,
    kmRecorridos: 0,
    costoPeajes: 0,
    consumoGalones: 0,
    costoCombustible: 0,
    costoTotal: 0,
    estado: "Programado",
    observaciones: "",
    cliente: "Inmobiliaria Caribe Ltda.",
    direccionOrigen: "Zona franca Santander",
    direccionDestino: "Bocagrande, Cartagena",
    horaLlegada: "",
    cantidadPeajes: 0,
    tiempoRecorridoMin: 0,
  },
  {
    id: "VIA-0007",
    fecha: "2026-08-11",
    rutaId: "RT-03",
    ciudadDestino: "Santa Marta",
    vehiculoId: "VEH-03",
    placa: "NXR022",
    conductorId: "CON-01",
    conductorNombre: "Cristian Ortiz",
    despachosIncluidos: "DES-0016",
    numeroObrasIncluidas: 1,
    horaSalida: "07:00",
    kmInicial: 0,
    kmFinal: 0,
    kmRecorridos: 0,
    costoPeajes: 0,
    consumoGalones: 0,
    costoCombustible: 0,
    costoTotal: 0,
    estado: "Programado",
    observaciones: "",
    cliente: "Inmobiliaria Caribe Ltda.",
    direccionOrigen: "Barranquilla",
    direccionDestino: "Rodadero Norte, Santa Marta",
    horaLlegada: "",
    cantidadPeajes: 0,
    tiempoRecorridoMin: 0,
  },
  {
    id: "VIA-0008",
    fecha: "2026-08-12",
    rutaId: "RT-01",
    ciudadDestino: "Cartagena",
    vehiculoId: "VEH-01",
    placa: "LWY380",
    conductorId: "CON-03",
    conductorNombre: "William Rueda",
    despachosIncluidos: "DES-0019",
    numeroObrasIncluidas: 1,
    horaSalida: "05:00",
    kmInicial: 0,
    kmFinal: 0,
    kmRecorridos: 0,
    costoPeajes: 0,
    consumoGalones: 0,
    costoCombustible: 0,
    costoTotal: 0,
    estado: "Programado",
    observaciones: "",
    cliente: "Constructora del Norte S.A.S.",
    direccionOrigen: "Zona franca Santander",
    direccionDestino: "Av. Circunvalar, Barranquilla",
    horaLlegada: "",
    cantidadPeajes: 0,
    tiempoRecorridoMin: 0,
  },
  {
    id: "VIA-0009",
    fecha: "2026-08-03",
    rutaId: "RT-02",
    ciudadDestino: "Bogotá",
    vehiculoId: "VEH-02",
    placa: "NXR036",
    conductorId: "CON-02",
    conductorNombre: "Didier Medina",
    despachosIncluidos: "DES-0011",
    numeroObrasIncluidas: 1,
    horaSalida: "06:00",
    kmInicial: 22500,
    kmFinal: 22920,
    kmRecorridos: 420,
    costoPeajes: 32000,
    consumoGalones: 52.5,
    costoCombustible: 777000,
    costoTotal: 809000,
    estado: "Cancelado",
    observaciones: "Cancelado por lluvias",
    cliente: "Desarrollos Bogotá S.A.",
    direccionOrigen: "Bucaramanga",
    direccionDestino: "Usaquén, Bogotá",
    horaLlegada: "",
    cantidadPeajes: 0,
    tiempoRecorridoMin: 0,
  },
  {
    id: "VIA-0010",
    fecha: "2026-08-02",
    rutaId: "RT-03",
    ciudadDestino: "Barranquilla",
    vehiculoId: "VEH-05",
    placa: "LWY387",
    conductorId: "CON-04",
    conductorNombre: "Cesar Rangel",
    despachosIncluidos: "DES-0001",
    numeroObrasIncluidas: 1,
    horaSalida: "08:00",
    kmInicial: 11500,
    kmFinal: 11620,
    kmRecorridos: 120,
    costoPeajes: 15000,
    consumoGalones: 12,
    costoCombustible: 166800,
    costoTotal: 181800,
    estado: "Completado",
    observaciones: "Entrega exitosa",
    cliente: "Constructora del Norte S.A.S.",
    direccionOrigen: "Cartagena",
    direccionDestino: "Calle 123, Barranquilla",
    horaLlegada: "10:30",
    cantidadPeajes: 1,
    tiempoRecorridoMin: 150,
  },
];

export const indicadores: Indicador[] = [
  { id: "KPI-01", nombre: "Despachos programados", descripcion: "Total de despachos programados en el período", periodo: "Semanal", valorActual: 24, meta: "—", unidad: "N°", tendencia: "stable", observaciones: "" },
  { id: "KPI-02", nombre: "Despachos entregados a tiempo", descripcion: "% de despachos entregados en la fecha programada", periodo: "Semanal", valorActual: 87, meta: "95%", unidad: "%", tendencia: "up", observaciones: "" },
  { id: "KPI-03", nombre: "Costo total de viajes", descripcion: "Suma de costos totales de todos los viajes del período", periodo: "Semanal", valorActual: 4250000, meta: "—", unidad: "COP", tendencia: "up", observaciones: "" },
  { id: "KPI-04", nombre: "Costo promedio por viaje", descripcion: "Promedio de costo total por viaje realizado", periodo: "Semanal", valorActual: 425000, meta: "—", unidad: "COP", tendencia: "stable", observaciones: "" },
  { id: "KPI-05", nombre: "Km recorridos totales", descripcion: "Suma de kilómetros recorridos en el período", periodo: "Semanal", valorActual: 1840, meta: "—", unidad: "Km", tendencia: "up", observaciones: "" },
  { id: "KPI-06", nombre: "Costo por Km", descripcion: "Costo promedio por kilómetro recorrido", periodo: "Semanal", valorActual: 2309, meta: "—", unidad: "COP/Km", tendencia: "down", observaciones: "" },
  { id: "KPI-07", nombre: "Utilización de flota", descripcion: "% de la flota en uso activo", periodo: "Semanal", valorActual: 60, meta: "80%", unidad: "%", tendencia: "stable", observaciones: "" },
  { id: "KPI-08", nombre: "Obras con dirección pendiente", descripcion: "Obras que no tienen dirección completa registrada", periodo: "Permanente", valorActual: 12, meta: "0", unidad: "N°", tendencia: "stable", observaciones: "" },
];

export const logs: LogEntry[] = [
  { fechaHora: "2026-08-01T10:30:00Z", usuario: "admin", modulo: "VIAJES", accion: "Crear", idRegistro: "VIA-0001", campoModificado: "", valorAnterior: "", valorNuevo: "", detalle: "Creación de viaje VIA-0001" },
  { fechaHora: "2026-08-01T11:15:00Z", usuario: "admin", modulo: "VEHICULOS", accion: "Editar", idRegistro: "VEH-01", campoModificado: "kmActual", valorAnterior: "14500", valorNuevo: "15000", detalle: "Actualización KM VEH-01" },
  { fechaHora: "2026-08-01T14:00:00Z", usuario: "admin", modulo: "PROGRAMACION", accion: "Crear", idRegistro: "DES-0001", campoModificado: "", valorAnterior: "", valorNuevo: "", detalle: "Creación de despacho DES-0001" },
  { fechaHora: "2026-08-02T09:00:00Z", usuario: "admin", modulo: "VIAJES", accion: "Editar", idRegistro: "VIA-0002", campoModificado: "estado", valorAnterior: "Programado", valorNuevo: "En ruta", detalle: "Cambio de estado VIA-0002" },
  { fechaHora: "2026-08-02T10:30:00Z", usuario: "admin", modulo: "CONDUCTORES", accion: "Editar", idRegistro: "CON-03", campoModificado: "vehiculoAsignadoId", valorAnterior: "VEH-03", valorNuevo: "null", detalle: "Desasignación de vehículo CON-03" },
  { fechaHora: "2026-08-02T15:00:00Z", usuario: "admin", modulo: "OBRAS", accion: "Crear", idRegistro: "OB-036", campoModificado: "", valorAnterior: "", valorNuevo: "", detalle: "Creación de obra OB-036" },
  { fechaHora: "2026-08-03T08:00:00Z", usuario: "admin", modulo: "PROGRAMACION", accion: "Editar", idRegistro: "DES-0005", campoModificado: "estado", valorAnterior: "En preparación", valorNuevo: "Despachado", detalle: "Cambio de estado DES-0005" },
  { fechaHora: "2026-08-03T11:00:00Z", usuario: "admin", modulo: "VIAJES", accion: "Crear", idRegistro: "VIA-0003", campoModificado: "", valorAnterior: "", valorNuevo: "", detalle: "Creación de viaje VIA-0003" },
  { fechaHora: "2026-08-03T16:00:00Z", usuario: "admin", modulo: "VEHICULOS", accion: "Editar", idRegistro: "VEH-04", campoModificado: "estado", valorAnterior: "Activo", valorNuevo: "En taller", detalle: "VEH-04 ingresa a taller" },
  { fechaHora: "2026-08-04T09:00:00Z", usuario: "admin", modulo: "PROGRAMACION", accion: "Importar", idRegistro: "DES-0017", campoModificado: "", valorAnterior: "", valorNuevo: "", detalle: "Importación de despacho desde Excel" },
];
