-- ============================================
-- DESHABILITAR RLS EN TODAS LAS TABLAS
-- Copiar y pegar en Supabase SQL Editor
-- ============================================

ALTER TABLE vehiculos DISABLE ROW LEVEL SECURITY;
ALTER TABLE conductores DISABLE ROW LEVEL SECURITY;
ALTER TABLE clientes DISABLE ROW LEVEL SECURITY;
ALTER TABLE obras DISABLE ROW LEVEL SECURITY;
ALTER TABLE rutas DISABLE ROW LEVEL SECURITY;
ALTER TABLE despachos DISABLE ROW LEVEL SECURITY;
ALTER TABLE viajes DISABLE ROW LEVEL SECURITY;
ALTER TABLE combustible DISABLE ROW LEVEL SECURITY;
ALTER TABLE peajes DISABLE ROW LEVEL SECURITY;
ALTER TABLE indicadores DISABLE ROW LEVEL SECURITY;
ALTER TABLE log_eventos DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE parametros DISABLE ROW LEVEL SECURITY;
